/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rreal;
import static com.sun.java.accessibility.util.AWTEventMonitor.addActionListener;
import javax.swing.ImageIcon;
import java.awt.Color;
import static java.awt.Color.BLACK;
import static java.awt.Color.WHITE;
import static java.awt.Color.red;
import static java.awt.Color.yellow;
import java.awt.event.MouseListener;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.PrintWriter;
import javaapplication18.body;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import pprofile.profile;
//import javax.swing.JFrame;
//import java.awt.Color.BLACK;
/**
 *
 * @author noor
 */
public class real extends javax.swing.JInternalFrame {
    int score=0;
    int quest=0;
    
    public real() {
        initComponents();
    }
    int count=0;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        J1 = new javax.swing.JLabel();
        J2 = new javax.swing.JLabel();
        J3 = new javax.swing.JLabel();
        J4 = new javax.swing.JLabel();
        J5 = new javax.swing.JLabel();
        J6 = new javax.swing.JLabel();
        J7 = new javax.swing.JLabel();
        J8 = new javax.swing.JLabel();
        J9 = new javax.swing.JLabel();
        J10 = new javax.swing.JLabel();
        J11 = new javax.swing.JLabel();
        J12 = new javax.swing.JLabel();
        J13 = new javax.swing.JLabel();
        J14 = new javax.swing.JLabel();
        J15 = new javax.swing.JLabel();
        Z50 = new javax.swing.JLabel();
        ZAudi = new javax.swing.JLabel();
        ZPhone = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rreal/fune a frend.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rreal/audience pole.jpg"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rreal/5050.jpg"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jButton1.setText("NEXT");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 10, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        t2.setEditable(false);
        t2.setBackground(new java.awt.Color(0, 0, 0));
        t2.setForeground(new java.awt.Color(255, 255, 255));
        t2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 5, true));
        t2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t2MouseClicked(evt);
            }
        });

        t3.setEditable(false);
        t3.setBackground(new java.awt.Color(0, 0, 0));
        t3.setForeground(new java.awt.Color(255, 255, 255));
        t3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 5, true));
        t3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t3MouseClicked(evt);
            }
        });
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });

        t4.setEditable(false);
        t4.setBackground(new java.awt.Color(0, 0, 0));
        t4.setForeground(new java.awt.Color(255, 255, 255));
        t4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 5, true));
        t4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t4MouseClicked(evt);
            }
        });

        t5.setEditable(false);
        t5.setBackground(new java.awt.Color(0, 0, 0));
        t5.setForeground(new java.awt.Color(255, 255, 255));
        t5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 5, true));
        t5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t5MouseClicked(evt);
            }
        });
        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("\n\n\t      PRESS NEXT TO START\n");
        jTextArea1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 6, true));
        jScrollPane1.setViewportView(jTextArea1);

        jLabel5.setMaximumSize(new java.awt.Dimension(1723, 2964));
        jLabel5.setPreferredSize(new java.awt.Dimension(1723, 2964));

        J1.setBackground(new java.awt.Color(0, 0, 0));
        J1.setForeground(new java.awt.Color(255, 255, 255));
        J1.setText("1 RUPEE");

        J2.setBackground(new java.awt.Color(0, 0, 0));
        J2.setForeground(new java.awt.Color(255, 255, 255));
        J2.setText("2 RUPEES");

        J3.setBackground(new java.awt.Color(0, 0, 0));
        J3.setForeground(new java.awt.Color(255, 255, 255));
        J3.setText("3 RUPEES");

        J4.setBackground(new java.awt.Color(0, 0, 0));
        J4.setForeground(new java.awt.Color(255, 255, 255));
        J4.setText("4 RUPEES");

        J5.setBackground(new java.awt.Color(0, 0, 0));
        J5.setForeground(new java.awt.Color(255, 255, 255));
        J5.setText("5 RUPEES");

        J6.setBackground(new java.awt.Color(0, 0, 0));
        J6.setForeground(new java.awt.Color(255, 255, 255));
        J6.setText("6 RUPEES");

        J7.setBackground(new java.awt.Color(0, 0, 0));
        J7.setForeground(new java.awt.Color(255, 255, 255));
        J7.setText("7 RUPEES");

        J8.setBackground(new java.awt.Color(0, 0, 0));
        J8.setForeground(new java.awt.Color(255, 255, 255));
        J8.setText("8 RUPEES");

        J9.setBackground(new java.awt.Color(0, 0, 0));
        J9.setForeground(new java.awt.Color(255, 255, 255));
        J9.setText("9 RUPEES");

        J10.setBackground(new java.awt.Color(0, 0, 0));
        J10.setForeground(new java.awt.Color(255, 255, 255));
        J10.setText("10 RUPEES");

        J11.setBackground(new java.awt.Color(0, 0, 0));
        J11.setForeground(new java.awt.Color(255, 255, 255));
        J11.setText("11 RUPEES");

        J12.setBackground(new java.awt.Color(0, 0, 0));
        J12.setForeground(new java.awt.Color(255, 255, 255));
        J12.setText("12 RUPEES");

        J13.setBackground(new java.awt.Color(0, 0, 0));
        J13.setForeground(new java.awt.Color(255, 255, 255));
        J13.setText("13 RUPEES");

        J14.setBackground(new java.awt.Color(0, 0, 0));
        J14.setForeground(new java.awt.Color(255, 255, 255));
        J14.setText("14 RUPEES");

        J15.setBackground(new java.awt.Color(0, 0, 0));
        J15.setForeground(new java.awt.Color(255, 255, 255));
        J15.setText("15 RUPEES");

        Z50.setFont(new java.awt.Font("Tunga", 1, 24)); // NOI18N
        Z50.setForeground(new java.awt.Color(255, 255, 255));
        Z50.setText("      50-50");

        ZAudi.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        ZAudi.setForeground(new java.awt.Color(255, 255, 255));
        ZAudi.setText("  Audience Pole");

        ZPhone.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        ZPhone.setForeground(new java.awt.Color(255, 255, 255));
        ZPhone.setText("  Phone A Friend");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(108, 108, 108)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ZPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ZAudi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Z50, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(291, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(J14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(J13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(J12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(J10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(J9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(J8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(J7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(J6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(J4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(J3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(J1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(J2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(J5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(J11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(J15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(108, 108, 108))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(J15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(J14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(J13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(J12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(J11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(J10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ZAudi)
                            .addComponent(Z50, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ZPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(J9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(J8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(J7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(J6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(J5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(J4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(J3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(J2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(J1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(144, 144, 144))
        );

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, 0));
        jMenuItem2.setText("Back to main menu");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:
        this.getContentPane().setBackground(Color.black);
    }//GEN-LAST:event_jPanel1MouseMoved

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        t5.setForeground(WHITE);
        t2.setForeground(WHITE);
        t3.setForeground(WHITE);
        t4.setForeground(WHITE);
        t2.setBackground(BLACK);
        t3.setBackground(BLACK);
        t4.setBackground(BLACK);
        t5.setBackground(BLACK);
        quest=quest+1;
        
        score=quest;
        if(quest==1)//d
        {   
            
            jButton1.setEnabled(false);
            jTextArea1.setText("In Matric, What grade did Gandhi score in Pak Studies");
            t2.setText("A)  B");
            t3.setText("B)  C");
            t4.setText("C)  A");
            t5.setText("D)  LOL");
        }
        if(quest==2)//b
        {
            J1.setForeground(yellow);
            jButton1.setEnabled(false);
            jTextArea1.setText("The Mogul Empire thrived from the 16th to the 18th Centuries, \nprimarily in which country?");
            t2.setText("A)  UK");
            t3.setText("B)  INDIA");
            t4.setText("C)  JAPAN");
            t5.setText("D)  TURKEY");
        }
        if(quest==3)//b
        {
            J2.setForeground(yellow);
            jButton1.setEnabled(false);
            jTextArea1.setText("What is the solution of (31/14)14");
            t2.setText("A)  3");
            t3.setText("B)  31");
            t4.setText("C)  21");
            t5.setText("D)  13");
        }
        if(quest==4)//a
        {
            J3.setForeground(yellow);
            jButton1.setEnabled(false);
            jTextArea1.setText("Which U.S. state was named by the U.S. Congress in 1800, \nand meant \"land of the Indians\"?");
            t2.setText("A)  INDIANA");
            t3.setText("B)  GUIANA");
            t4.setText("C)  JAMAICA");
            t5.setText("D)  SAINT LUCIA");
        }
        if(quest==5)//d
        {
            J4.setForeground(yellow);
            jButton1.setEnabled(false);
            jTextArea1.setText("Who killed Abraham Lincoln?");
            t2.setText("A)  MICHEAL DE GENERES");
            t3.setText("B)  GEORGE D.THOMAS");
            t4.setText("C)  GERIME TAYLOR");
            t5.setText("D)  JOHN WILKES BOOTH");
        }
        if(quest==6)//b
        {
            J5.setForeground(yellow);
            jButton1.setEnabled(false);
            jTextArea1.setText("How many voyages did Christopher Columbus make from \nEurope to the New World?");
            t2.setText("A)  3");
            t3.setText("B)  4");
            t4.setText("C)  5");
            t5.setText("D)  1");
        }
        if(quest==7)//c
        {
            J6.setForeground(yellow);
            jButton1.setEnabled(false);
            jTextArea1.setText("Until the 1750's, this country was the world's only \nsource of diamonds. It wasn't South Africa. What was it?");
            t2.setText("A)  EGYPT");
            t3.setText("B)  AUSTRALIA");
            t4.setText("C)  INDIA");
            t5.setText("D)  BRAZIL");
        }
        if(quest==8)//c
        {
            J7.setForeground(yellow);
            jButton1.setEnabled(false);
            jTextArea1.setText("The first aerial war photograph was taken from a \nballoon, during what war?");
            t2.setText("A)  WORLD WAR 2");
            t3.setText("B)  WORLD WAR 1");
            t4.setText("C)  US CIVIL WAR");
            t5.setText("D)  WAR OF INDEPENDENCE");
        }
        if(quest==9)//a
        {
            J8.setForeground(yellow);
            jButton1.setEnabled(false);
            jTextArea1.setText("What is the cheapest yet tastiest thing to eat in Pakistan \nwhen you are hungry");
            t2.setText("A)  ANDAY WALA BURGER");
            t3.setText("B)  BIRYANI");
            t4.setText("C)  AALU GULEHRI");
            t5.setText("D)  HONG KONG K CHOLLE");
        }
        if(quest==10)//d
        {
            J9.setForeground(yellow);
            jButton1.setEnabled(false);
            jTextArea1.setText("What was the name of the Christopher Columbus' flagship - the \nship on which Columbus travelled in his 1492 voyage to the new world?");
            t2.setText("A)  CHISITI TRAVELERS");
            t3.setText("B)  SANT JOSEPH");
            t4.setText("C)  THE TITANIC");
            t5.setText("D)  SANT MARIA");
        }
        if(quest==11)//c
        {
            J10.setForeground(yellow);
            jButton1.setEnabled(false);
            jTextArea1.setText("Who was the only U.S. president to be impeached?");
            t2.setText("A)  MARKUS TRESCOTHIC");
            t3.setText("B)  ANDREW JOHNSON");
            t4.setText("C)  GEORGE WASHINGTON");
            t5.setText("D)  GEORGE BUSH");
        }
        if(quest==12)//b
        {
            J11.setForeground(yellow);
            jButton1.setEnabled(false);
            jTextArea1.setText("On July 16, 1945, three weeks before the atomic bomb was dropped \non Hiroshima, it was tested for the first time where?");
            t2.setText("A)  NEW JERSEY");
            t3.setText("B)  NEW MEXICO");
            t4.setText("C)  NEW ALABAMA");
            t5.setText("D)  NEW YORK");
        }
        if(quest==13)//b
        {
            J12.setForeground(yellow);
            jButton1.setEnabled(false);
            jTextArea1.setText("The current U.S. flag was adopted on July 4 of what year?");
            t2.setText("A)  1568");
            t3.setText("B)  1960");
            t4.setText("C)  1888");
            t5.setText("D)  1776");
        }
        if(quest==14)//b
        {
            J13.setForeground(yellow);
            jButton1.setEnabled(false);
            jTextArea1.setText("Working in the Netherlands in 1714, which German-born scientist \ninvented the first modern thermometer?");
            t2.setText("A)  JOSRPH CELSIUS");
            t3.setText("B)  GABRIEL FAHRENHEIT");
            t4.setText("C)  ADAM DEGREES");
            t5.setText("D)  GRAHAM THARMA");
        }
        if(quest==15)//d
        {
            J14.setForeground(yellow);
            jButton1.setEnabled(false);
            jTextArea1.setText(" The world's first automobile license plates showed up in 1893, \nin which country?");
            t2.setText("A)  USA");
            t3.setText("B)  SPAIN");
            t4.setText("C)  GERMANY");
            t5.setText("D)  FRANCE");
        }
        if(quest==16)
        {
            jButton1.setEnabled(false);
            ending();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        ZAudi.setForeground(red);
        if(quest==1 && jLabel2.isFocusable())
        {
            t3.setForeground(BLACK);
            t4.setForeground(BLACK);
            t2.setForeground(BLACK);
            disableAudi();
        }
        if(quest==2 && jLabel2.isFocusable())
        {
            t2.setForeground(BLACK);
            t4.setForeground(BLACK);
            t5.setForeground(BLACK);
            disableAudi();
        }
        if(quest==3 && jLabel2.isFocusable())
        {
            t2.setForeground(BLACK);
            t4.setForeground(BLACK);
            t5.setForeground(BLACK);
            disableAudi();
        }
        if(quest==4 && jLabel2.isFocusable())
        {
            t3.setForeground(BLACK);
            t4.setForeground(BLACK);
            t5.setForeground(BLACK);
            disableAudi();
        }
        if(quest==5 && jLabel2.isFocusable())
        {
            t2.setForeground(BLACK);
            t4.setForeground(BLACK);
            t3.setForeground(BLACK);
            disableAudi();
        }
        if(quest==6 && jLabel2.isFocusable())
        {
            t2.setForeground(BLACK);
            t4.setForeground(BLACK);
            t5.setForeground(BLACK);
            disableAudi();
        }
        if(quest==7 && jLabel2.isFocusable())
        {
            t2.setForeground(BLACK);
            t5.setForeground(BLACK);
            t3.setForeground(BLACK);
            disableAudi();
        }
        if(quest==8 && jLabel2.isFocusable())
        {
            t3.setForeground(BLACK);
            t2.setForeground(BLACK);
            t5.setForeground(BLACK);
            disableAudi();
        }
        if(quest==9 && jLabel2.isFocusable())
        {
            t5.setForeground(BLACK);
            t4.setForeground(BLACK);
            t3.setForeground(BLACK);
            disableAudi();
        }
        if(quest==10 && jLabel2.isFocusable())
        {
            t3.setForeground(BLACK);
            t4.setForeground(BLACK);
            t2.setForeground(BLACK);
            disableAudi();
        }
        if(quest==11 && jLabel2.isFocusable())
        {
            t5.setForeground(BLACK);
            t2.setForeground(BLACK);
            t3.setForeground(BLACK);
            disableAudi();
        }
        if(quest==12 && jLabel2.isFocusable())
        {
            t2.setForeground(BLACK);
            t5.setForeground(BLACK);
            t4.setForeground(BLACK);
            disableAudi();
        }
        if(quest==13 && jLabel2.isFocusable())
        {
            t2.setForeground(BLACK);
            t4.setForeground(BLACK);
            t5.setForeground(BLACK);
            disableAudi();
        }
        if(quest==14 && jLabel2.isFocusable())
        {
            t2.setForeground(BLACK);
            t4.setForeground(BLACK);
            t5.setForeground(BLACK);
            disableAudi();
        }
        if(quest==15 && jLabel2.isFocusable())
        {
            t2.setForeground(BLACK);
            t3.setForeground(BLACK);
            t4.setForeground(BLACK);
            disableAudi();
        }
    }                                    
    public void disableAudi()
    {
        MouseListener[] mouseListeners = jLabel2.getMouseListeners();
            for (int i = 0; i < mouseListeners.length; i++) {
                jLabel2.removeMouseListener(mouseListeners[i]);
            }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       
        ZPhone.setForeground(red);
        if(quest==1 && jLabel2.isFocusable())
        {
            t3.setForeground(BLACK);
            disablePhone();
        }
        if(quest==2 && jLabel2.isFocusable())
        {
            t2.setForeground(BLACK);
            disablePhone();
        }
        if(quest==3 && jLabel2.isFocusable())
        {
            t5.setForeground(BLACK);
            disablePhone();
        }
        if(quest==4 && jLabel2.isFocusable())
        {
            t3.setForeground(BLACK);
            disablePhone();;
        }
        if(quest==5 && jLabel2.isFocusable())
        {
            t3.setForeground(BLACK);
            disablePhone();
        }
        if(quest==6 && jLabel2.isFocusable())
        {
            t5.setForeground(BLACK);
            disablePhone();
        }
        if(quest==7 && jLabel2.isFocusable())
        {
            t3.setForeground(BLACK);
            disablePhone();
        }
        if(quest==8 && jLabel2.isFocusable())
        {
            
            t5.setForeground(BLACK);
            disablePhone();
        }
        if(quest==9 && jLabel2.isFocusable())
        {
            
            t3.setForeground(BLACK);
            disablePhone();
        }
        if(quest==10 && jLabel2.isFocusable())
        {
            t3.setForeground(BLACK);
            disablePhone();
        }
        if(quest==11 && jLabel2.isFocusable())
        {
            t5.setForeground(BLACK);
            disablePhone();
        }
        if(quest==12 && jLabel2.isFocusable())
        {
            
            t4.setForeground(BLACK);
            disablePhone();
        }
        if(quest==13 && jLabel2.isFocusable())
        {
            
            t4.setForeground(BLACK);
            disablePhone();
        }
        if(quest==14 && jLabel2.isFocusable())
        {
            t2.setForeground(BLACK);
            disablePhone();
        }
        if(quest==15 && jLabel2.isFocusable())
        {
            
            t4.setForeground(BLACK);
            disablePhone();
        }
    }                                    
    public void disablePhone()
    {
        MouseListener[] mouseListeners = jLabel2.getMouseListeners();
            for (int i = 0; i < mouseListeners.length; i++) {
                jLabel1.removeMouseListener(mouseListeners[i]);
            }
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Z50.setForeground(red);
        if(quest==1 && jLabel3.isFocusable())
        {
            t3.setForeground(BLACK);
            t4.setForeground(BLACK);
            disable50_50();
        }
        if(quest==2 && jLabel3.isFocusable())
        {
            t2.setForeground(BLACK);
            t4.setForeground(BLACK);
            disable50_50();
        }
        if(quest==3 && jLabel3.isFocusable())
        {
            t2.setForeground(BLACK);
            t4.setForeground(BLACK);
            disable50_50();
        }
        if(quest==4 && jLabel3.isFocusable())
        {
            t3.setForeground(BLACK);
            t5.setForeground(BLACK);
            disable50_50();
        }
        if(quest==5 && jLabel3.isFocusable())
        {
            t2.setForeground(BLACK);
            t4.setForeground(BLACK);
            disable50_50();
        }
        if(quest==6 && jLabel3.isFocusable())
        {
            t2.setForeground(BLACK);
            t5.setForeground(BLACK);
            disable50_50();
        }
        if(quest==7 && jLabel3.isFocusable())
        {
            t2.setForeground(BLACK);
            t5.setForeground(BLACK);
            disable50_50();
        }
        if(quest==8 && jLabel3.isFocusable())
        {
            t2.setForeground(BLACK);
            t5.setForeground(BLACK);
            disable50_50();
        }
        if(quest==9 && jLabel3.isFocusable())
        {
            t5.setForeground(BLACK);
            t4.setForeground(BLACK);
            disable50_50();
        }
        if(quest==10 && jLabel3.isFocusable())
        {
            t3.setForeground(BLACK);
            t4.setForeground(BLACK);
            disable50_50();
        }
        if(quest==11 && jLabel3.isFocusable())
        {
            t5.setForeground(BLACK);
            t2.setForeground(BLACK);
            disable50_50();
        }
        if(quest==12 && jLabel3.isFocusable())
        {
            t2.setForeground(BLACK);
            t5.setForeground(BLACK);
            disable50_50();
        }
        if(quest==13 && jLabel3.isFocusable())
        {
            t2.setForeground(BLACK);
            t4.setForeground(BLACK);
            disable50_50();
        }
        if(quest==14 && jLabel3.isFocusable())
        {
            t2.setForeground(BLACK);
            t4.setForeground(BLACK);
            disable50_50();
        }
        if(quest==15 && jLabel3.isFocusable())
        {
            t3.setForeground(BLACK);
            t4.setForeground(BLACK);
            disable50_50();
        }
    }//GEN-LAST:event_jLabel3MouseClicked
    public void disable50_50()
    {
        MouseListener[] mouseListeners = jLabel3.getMouseListeners();
            for (int i = 0; i < mouseListeners.length; i++) {
                jLabel3.removeMouseListener(mouseListeners[i]);
            }
    }
    private void t2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t2MouseClicked
        // TODO add your handling code here:
       MouseListener[] mouseListeners = t2.getMouseListeners();
            for (int i = 0; i < mouseListeners.length; i++) {
                t3.removeMouseListener(mouseListeners[i]);
                t4.removeMouseListener(mouseListeners[i]);
                t5.removeMouseListener(mouseListeners[i]);
            }
        if (quest ==4 || quest==9  )
        {   
            jButton1.setEnabled(true);
            t2.setOpaque(true);
            t2.setForeground(Color.BLACK);
            t2.setBackground(Color.green);
            
            t3.setOpaque(true);
            t3.setForeground(Color.WHITE);
            t3.setBackground(Color.BLACK);
        
            t4.setOpaque(true);
            t4.setForeground(Color.WHITE);
            t4.setBackground(Color.BLACK);
        
            t5.setOpaque(true);
            t5.setForeground(Color.WHITE);
            t5.setBackground(Color.BLACK);
        }
        else
        {
            jButton1.setEnabled(false);
            ending();
            t2.setOpaque(true);
            t2.setForeground(Color.BLACK);
            t2.setBackground(Color.RED);            
        }
    }//GEN-LAST:event_t2MouseClicked

    private void t3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t3MouseClicked
        // TODO add your handling code here:
       
        if (quest ==2 || quest==3 || quest==6 || quest==12 || quest==13 || quest==14 )
        {
            jButton1.setEnabled(true);
            t3.setOpaque(true);
            t3.setForeground(Color.BLACK);
            t3.setBackground(Color.green);
            
            t2.setOpaque(true);
            t2.setForeground(Color.WHITE);
            t2.setBackground(Color.BLACK);
        
            t4.setOpaque(true);
            t4.setForeground(Color.WHITE);
            t4.setBackground(Color.BLACK);
        
            t5.setOpaque(true);
            t5.setForeground(Color.WHITE);
            t5.setBackground(Color.BLACK);
        }else
        {   
            jButton1.setEnabled(false);
            ending();
            t3.setOpaque(true);
            t3.setForeground(Color.BLACK);
            t3.setBackground(Color.RED);            
        }
    }//GEN-LAST:event_t3MouseClicked

    private void t4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t4MouseClicked
        // TODO add your handling code here:
        
        if (quest ==7 || quest==8 || quest==11 )
        {
            jButton1.setEnabled(true);
            t4.setOpaque(true);
            t4.setForeground(Color.BLACK);
            t4.setBackground(Color.green);
            
            t2.setOpaque(true);
            t2.setForeground(Color.WHITE);
            t2.setBackground(Color.BLACK);
        
            t3.setOpaque(true);
            t3.setForeground(Color.WHITE);
            t3.setBackground(Color.BLACK);
        
            t5.setOpaque(true);
            t5.setForeground(Color.WHITE);
            t5.setBackground(Color.BLACK);
        }
         else
        {
            jButton1.setEnabled(false);
            ending();
            t4.setOpaque(true);
            t4.setForeground(Color.BLACK);
            t4.setBackground(Color.RED);            
        }
    }//GEN-LAST:event_t4MouseClicked

    private void t5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t5MouseClicked
        
        
        if (quest ==1 || quest==5 || quest==10 || quest==15  )
        {
            jButton1.setEnabled(true);
            t5.setOpaque(true);
            t5.setForeground(Color.BLACK);
            t5.setBackground(Color.green);
            
            t2.setOpaque(true);
            t2.setForeground(Color.WHITE);
            t2.setBackground(Color.BLACK);
        
            t4.setOpaque(true);
            t4.setForeground(Color.WHITE);
            t4.setBackground(Color.BLACK);
        
            t3.setOpaque(true);
            t3.setForeground(Color.WHITE);
            t3.setBackground(Color.BLACK);
            
            
        }
        else
        {
            
            jButton1.setEnabled(false);
            ending();
            t5.setOpaque(true);
            t5.setForeground(Color.BLACK);
            t5.setBackground(Color.RED);
            
        }
    }//GEN-LAST:event_t5MouseClicked
    public void ending()
    {
        final JFrame parent = new JFrame();
        JButton button = new JButton();
        
        button.setText("Congratulations! Click me to claim your " +(score-1)+ " rupees");
        parent.add(button);
        parent.pack();
        
        parent.setVisible(true);
        
        button.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPanel1.setFocusable(false);
                String name = JOptionPane.showInputDialog(parent,
                        "What is your name?", null);
                String doing = JOptionPane.showInputDialog(parent,
                        "What will you do with this money?", null);
            try
        {
        FileWriter fw = new FileWriter("D:\\game.txt",true);
        BufferedWriter bw=new BufferedWriter(fw);
        PrintWriter pw;
        pw = new PrintWriter(bw);
        pw.write("Name:" +name + " Remarks:"+ doing+ " Money:" + (score-1)+"  ");
        pw.flush();
        pw.close();
        
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
            System.exit(0);
            
            }
        });
    }
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel J1;
    private javax.swing.JLabel J10;
    private javax.swing.JLabel J11;
    private javax.swing.JLabel J12;
    private javax.swing.JLabel J13;
    private javax.swing.JLabel J14;
    private javax.swing.JLabel J15;
    private javax.swing.JLabel J2;
    private javax.swing.JLabel J3;
    private javax.swing.JLabel J4;
    private javax.swing.JLabel J5;
    private javax.swing.JLabel J6;
    private javax.swing.JLabel J7;
    private javax.swing.JLabel J8;
    private javax.swing.JLabel J9;
    private javax.swing.JLabel Z50;
    private javax.swing.JLabel ZAudi;
    private javax.swing.JLabel ZPhone;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables
}
